spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/report_app?ApplicationName=TestSweetApp
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20 # Увеличить при необходимости
      leak-detection-threshold: 60000  # Включить детектор утечек
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
account_url: http://localhost:8080/api/v1/account/
operation_category_url: http://localhost:8081/api/v1/classifier/operation/category/
operation_url: http://localhost:8080/api/v1/account/
currency_url: http://localhost:8081/api/v1/classifier/currency/
server:
  port: 8082